name: Rust CI

on: [push, pull_request]

jobs:
  Container-Test-Job:
    runs-on: ubuntu-latest
    container:
      image: rust:1-slim-buster
      env:
        EXAMPLE: foo
    steps:
      - uses: actions/checkout@main
      - name: Apt Update
        run: DEBIAN_FRONTEND=noninteractive apt update
      - name: Install openssl-sys
        run: DEBIAN_FRONTEND=noninteractive apt install pkg-config -y
      - name: Run cargo check
        run: cargo check
      - name: Run cargo test
        run: cargo test
